objects/CustomRule__mdt/fields/Expression__c.field-meta.xml
<CustomField>
    <fullName>Expression__c</fullName>
    <description>Executes the logic of the child records with this given expression</description>
    <inlineHelpText>inform the number of the rule condition with &amp;&amp;, || and ()</inlineHelpText>
    <label>Expression</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/RuleCondition__mdt/fields/CustomRule__c.field-meta.xml
<CustomField>
    <fullName>CustomRule__c</fullName>
    <label>Custom rule</label>
    <referenceTo>CustomRule__mdt</referenceTo>
    <relationshipLabel>Rule conditions</relationshipLabel>
    <relationshipName>RuleConditions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

objects/RuleCondition__mdt/fields/Expression__c.field-meta.xml
<CustomField>
    <fullName>Expression__c</fullName>
    <label>Expression</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/CustomRuleMdtHandler.cls
public with sharing class CustomRuleMdtHandler {

	public static Map<String, Boolean> eval(Set<String> set_customRuleMdts, Map<String, SObject> map_values) {
		
		Map<String, Boolean> map_res = new Map<String, Boolean>();
		
		MassEvalHandler massEvalHand = new MassEvalHandler(map_values);
		List<String> lstConditions = new List<String>();
		for(CustomRule__mdt rules : [SELECT DeveloperName, Expression__c, (SELECT DeveloperName, Expression__c FROM RuleConditions__r ORDER BY Order__c) FROM CustomRule__mdt WHERE DeveloperName = :set_customRuleMdts]){
			System.debug('Eval ' + rules.DeveloperName);
			if(!lstConditions.isEmpty())lstConditions.clear();
			for(RuleCondition__mdt rulecond : rules.RuleConditions__r){
				lstConditions.add(rulecond.Expression__c);
			}
			System.debug('Expressions ' + rules.Expression__c);
			massEvalHand.expression = rules.Expression__c;
			massEvalHand.lstConditions = lstConditions;
			System.debug('Conditions ' + lstConditions);
			map_res.put(rules.DeveloperName, massEvalHand.eval());
		}
		return map_res;
    }
}